// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1_DAL.DBContext;

namespace _1_DAL.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211129142751_DA1_862_QLPM_Karaoke_V3")]
    partial class DA1_862_QLPM_Karaoke_V3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_1_DAL.Entities.ChiTietHoaDonBan", b =>
                {
                    b.Property<int>("IdchiTietHoaDonBan")
                        .HasColumnType("int")
                        .HasColumnName("IDChiTietHoaDonBan");

                    b.Property<double?>("DonGia")
                        .HasColumnType("float");

                    b.Property<int>("IdhoaDon")
                        .HasColumnType("int")
                        .HasColumnName("IDHoaDon");

                    b.Property<int>("IdmatHang")
                        .HasColumnType("int")
                        .HasColumnName("IDMatHang");

                    b.Property<string>("IdtranngThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("IDTranngThai")
                        .HasDefaultValueSql("((1))")
                        .IsFixedLength(true);

                    b.Property<string>("Idusername")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("IDUsername");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("IdchiTietHoaDonBan");

                    b.HasIndex("IdhoaDon");

                    b.HasIndex(new[] { "IdmatHang" }, "IX_ChiTietHoaDonBan_IDMatHang");

                    b.ToTable("ChiTietHoaDonBan");
                });

            modelBuilder.Entity("_1_DAL.Entities.ChiTietHoaDonNhap", b =>
                {
                    b.Property<int>("IdchiTietHoaDonNhap")
                        .HasColumnType("int")
                        .HasColumnName("IDChiTietHoaDonNhap");

                    b.Property<double?>("DonGiaNhap")
                        .HasColumnType("float");

                    b.Property<int>("IdhoaDon")
                        .HasColumnType("int")
                        .HasColumnName("IDHoaDon");

                    b.Property<int>("IdmatHang")
                        .HasColumnType("int")
                        .HasColumnName("IDMatHang");

                    b.Property<string>("IdtranngThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("IDTranngThai")
                        .HasDefaultValueSql("((1))")
                        .IsFixedLength(true);

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("IdchiTietHoaDonNhap");

                    b.HasIndex("IdhoaDon");

                    b.HasIndex(new[] { "IdmatHang" }, "IX_ChiTietHoaDonNhap_IDMatHang");

                    b.ToTable("ChiTietHoaDonNhap");
                });

            modelBuilder.Entity("_1_DAL.Entities.ChiTietThietBi", b =>
                {
                    b.Property<int>("IdchiTietThietBi")
                        .HasColumnType("int")
                        .HasColumnName("IDChiTietThietBi");

                    b.Property<double?>("DonGia")
                        .HasColumnType("float");

                    b.Property<string>("IdmaTb")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("IDMaTB");

                    b.Property<int>("Idphong")
                        .HasColumnType("int")
                        .HasColumnName("IDPhong");

                    b.Property<int?>("IdtranngThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDTranngThai")
                        .HasDefaultValueSql("((1))");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("IdchiTietThietBi");

                    b.HasIndex("Idphong");

                    b.HasIndex(new[] { "IdmaTb" }, "IX_ChiTietThietBi_IDMaTB");

                    b.ToTable("ChiTietThietBi");
                });

            modelBuilder.Entity("_1_DAL.Entities.ChucVu", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("IdtrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("IDTrangThai")
                        .HasDefaultValueSql("((1))")
                        .IsFixedLength(true);

                    b.Property<string>("TenChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("_1_DAL.Entities.CongThucTinh", b =>
                {
                    b.Property<int>("IdcongThucTinh")
                        .HasColumnType("int")
                        .HasColumnName("IDCongThucTinh");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("GiaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("((0))");

                    b.Property<double?>("GiaPhongVIP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("((0))");

                    b.Property<int?>("IdtrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("((1))");

                    b.Property<double?>("ThoiGianNhanUuDai1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("((0))");

                    b.Property<double?>("ThoiGianNhanUuDai2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("((0))");

                    b.Property<double?>("ThoiGianNhanUuDai3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("((0))");

                    b.Property<double?>("UuDai1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("((0))");

                    b.Property<double?>("UuDai2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("((0))");

                    b.Property<double?>("UuDai3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValueSql("((0))");

                    b.HasKey("IdcongThucTinh");

                    b.ToTable("CongThucTinh");
                });

            modelBuilder.Entity("_1_DAL.Entities.DonViTinh", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("IdtranngThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("IDTranngThai")
                        .HasDefaultValueSql("((1))")
                        .IsFixedLength(true);

                    b.Property<DateTime?>("NgayCapNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NguoiCapNhap")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValueSql("('admin')");

                    b.Property<string>("NguoiTao")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValueSql("('admin')");

                    b.Property<string>("TenDvt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenDVT");

                    b.HasKey("Id");

                    b.ToTable("DonViTinh");
                });

            modelBuilder.Entity("_1_DAL.Entities.HoaDonBanHang", b =>
                {
                    b.Property<int>("IdhoaDon")
                        .HasColumnType("int")
                        .HasColumnName("IDHoaDon");

                    b.Property<double?>("DonGiaPhong")
                        .HasColumnType("float");

                    b.Property<int?>("IdcongThucTinh")
                        .HasColumnType("int")
                        .HasColumnName("IDCongThucTinh");

                    b.Property<string>("IdmaKh")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("IDMaKH");

                    b.Property<string>("IdmaNv")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("IDMaNV");

                    b.Property<int?>("Idphong")
                        .HasColumnType("int")
                        .HasColumnName("IDPhong");

                    b.Property<int?>("IdtranngThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDTranngThai")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime?>("NgayCapNhap")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiBan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NguoiCapNhap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ThoiGianBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime");

                    b.HasKey("IdhoaDon");

                    b.HasIndex("IdcongThucTinh");

                    b.HasIndex(new[] { "IdmaKh" }, "IX_HoaDonBanHang_IDMaKH");

                    b.HasIndex(new[] { "IdmaNv" }, "IX_HoaDonBanHang_IDMaNV");

                    b.HasIndex(new[] { "Idphong" }, "IX_HoaDonBanHang_IDPhong");

                    b.ToTable("HoaDonBanHang");
                });

            modelBuilder.Entity("_1_DAL.Entities.HoaDonNhap", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("IdnhaCc")
                        .HasColumnType("int")
                        .HasColumnName("IDNhaCC");

                    b.Property<string>("IdnhanVienNhap")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("IDNhanVienNhap");

                    b.Property<string>("IdtranngThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("IDTranngThai")
                        .HasDefaultValueSql("((1))")
                        .IsFixedLength(true);

                    b.Property<DateTime?>("NgayCapNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NgayNhap")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength(true);

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NguoiCapNhap")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValueSql("('admin')");

                    b.Property<string>("NguoiTao")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValueSql("('admin')");

                    b.Property<double?>("TienThanhToan")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdnhaCc" }, "IX_HoaDonNhap_IDNhaCC");

                    b.HasIndex(new[] { "IdnhanVienNhap" }, "IX_HoaDonNhap_IDNhanVienNhap");

                    b.ToTable("HoaDonNhap");
                });

            modelBuilder.Entity("_1_DAL.Entities.KhachHang", b =>
                {
                    b.Property<string>("MaKh")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("MaKH");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<int?>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("Ho")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdtranngThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDTranngThai")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenDem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKh");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("_1_DAL.Entities.LoaiPhong", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<double?>("DonGia")
                        .HasColumnType("float");

                    b.Property<string>("IdtranngThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("IDTranngThai")
                        .HasDefaultValueSql("((1))")
                        .IsFixedLength(true);

                    b.Property<DateTime?>("NgayCapNhap")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("NguoiCapNhap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NguoiTao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenLoaiPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("LoaiPhong");
                });

            modelBuilder.Entity("_1_DAL.Entities.LoaiThietBi", b =>
                {
                    b.Property<string>("MaLoaiTb")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("MaLoaiTB");

                    b.Property<string>("IdtranngThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("IDTranngThai")
                        .HasDefaultValueSql("((1))")
                        .IsFixedLength(true);

                    b.Property<string>("TenLoai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("XuatXu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLoaiTb");

                    b.ToTable("LoaiThietBi");
                });

            modelBuilder.Entity("_1_DAL.Entities.MatHang", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<int?>("IddonViTinh")
                        .HasColumnType("int")
                        .HasColumnName("IDDonViTinh");

                    b.Property<int?>("IdtranngThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDTranngThai")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime?>("NgayCapNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NguoiCapNhap")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValueSql("('admin')");

                    b.Property<string>("NguoiTao")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValueSql("('admin')");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenMatHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IddonViTinh" }, "IX_MatHang_IDDonViTinh");

                    b.ToTable("MatHang");
                });

            modelBuilder.Entity("_1_DAL.Entities.NhaCungCap", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("IdtranngThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDTranngThai")
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime?>("NgayCapNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NguoiCapNhap")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValueSql("('admin')");

                    b.Property<string>("NguoiTao")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValueSql("('admin')");

                    b.Property<string>("TenNcc")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("TenNCC");

                    b.HasKey("Id");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("_1_DAL.Entities.NhanVien", b =>
                {
                    b.Property<string>("MaNv")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("MaNV");

                    b.Property<string>("Cmnd")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CMND");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("Ho")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("IdchucVu")
                        .HasColumnType("int")
                        .HasColumnName("IDChucVu");

                    b.Property<int?>("IdtranngThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDTranngThai")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Password")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Ten")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenDem")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("MaNv");

                    b.HasIndex(new[] { "IdchucVu" }, "IX_NhanVien_IDChucVu");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("_1_DAL.Entities.Phong", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<int?>("IdloaiPhong")
                        .HasColumnType("int")
                        .HasColumnName("IDLoaiPhong");

                    b.Property<int?>("Idtang")
                        .HasColumnType("int")
                        .HasColumnName("IDTang");

                    b.Property<string>("IdtranngThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("IDTranngThai")
                        .HasDefaultValueSql("((1))")
                        .IsFixedLength(true);

                    b.Property<DateTime?>("NgayCapNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NguoiCapNhap")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValueSql("('admin')");

                    b.Property<string>("NguoiTao")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValueSql("('admin')");

                    b.Property<int?>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValueSql("((1))");

                    b.HasKey("Id");

                    b.HasIndex("Idtang");

                    b.HasIndex(new[] { "IdloaiPhong" }, "IX_Phong_IDLoaiPhong");

                    b.ToTable("Phong");
                });

            modelBuilder.Entity("_1_DAL.Entities.Tang", b =>
                {
                    b.Property<int>("Idtang")
                        .HasColumnType("int")
                        .HasColumnName("IDTang");

                    b.Property<int?>("IdtrangThai")
                        .HasColumnType("int")
                        .HasColumnName("IDTrangThai");

                    b.Property<int?>("SoLuongPhong")
                        .HasColumnType("int");

                    b.Property<string>("TenTang")
                        .HasMaxLength(40)
                        .HasColumnType("nchar(40)")
                        .IsFixedLength(true);

                    b.HasKey("Idtang");

                    b.ToTable("Tang");
                });

            modelBuilder.Entity("_1_DAL.Entities.ThietBi", b =>
                {
                    b.Property<string>("MaTb")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("MaTB");

                    b.Property<double?>("DonGia")
                        .HasColumnType("float");

                    b.Property<string>("IdmaLoaiTb")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("IDMaLoaiTB");

                    b.Property<string>("IdtranngThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("IDTranngThai")
                        .HasDefaultValueSql("((1))")
                        .IsFixedLength(true);

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenTb")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenTB");

                    b.Property<int?>("TinhTrang")
                        .HasColumnType("int");

                    b.HasKey("MaTb");

                    b.HasIndex(new[] { "IdmaLoaiTb" }, "IX_ThietBi_IDMaLoaiTB");

                    b.ToTable("ThietBi");
                });

            modelBuilder.Entity("_1_DAL.Entities.ChiTietHoaDonBan", b =>
                {
                    b.HasOne("_1_DAL.Entities.HoaDonBanHang", "IdhoaDonNavigation")
                        .WithMany("ChiTietHoaDonBans")
                        .HasForeignKey("IdhoaDon")
                        .HasConstraintName("FK_ChiTietHoaDonBan_HoaDonBanHang")
                        .IsRequired();

                    b.HasOne("_1_DAL.Entities.MatHang", "IdmatHangNavigation")
                        .WithMany("ChiTietHoaDonBans")
                        .HasForeignKey("IdmatHang")
                        .HasConstraintName("FK_ChiTietHoaDonBan_MatHang")
                        .IsRequired();

                    b.Navigation("IdhoaDonNavigation");

                    b.Navigation("IdmatHangNavigation");
                });

            modelBuilder.Entity("_1_DAL.Entities.ChiTietHoaDonNhap", b =>
                {
                    b.HasOne("_1_DAL.Entities.HoaDonNhap", "IdhoaDonNavigation")
                        .WithMany("ChiTietHoaDonNhaps")
                        .HasForeignKey("IdhoaDon")
                        .HasConstraintName("FK_ChiTietHoaDonNhap_HoaDonNhap")
                        .IsRequired();

                    b.HasOne("_1_DAL.Entities.MatHang", "IdmatHangNavigation")
                        .WithMany("ChiTietHoaDonNhaps")
                        .HasForeignKey("IdmatHang")
                        .HasConstraintName("FK_ChiTietHoaDonNhap_MatHang1")
                        .IsRequired();

                    b.Navigation("IdhoaDonNavigation");

                    b.Navigation("IdmatHangNavigation");
                });

            modelBuilder.Entity("_1_DAL.Entities.ChiTietThietBi", b =>
                {
                    b.HasOne("_1_DAL.Entities.ThietBi", "IdmaTbNavigation")
                        .WithMany("ChiTietThietBis")
                        .HasForeignKey("IdmaTb")
                        .HasConstraintName("FK_ChiTietThietBi_ThietBi")
                        .IsRequired();

                    b.HasOne("_1_DAL.Entities.Phong", "IdphongNavigation")
                        .WithMany("ChiTietThietBis")
                        .HasForeignKey("Idphong")
                        .HasConstraintName("FK_ChiTietThietBi_Phong")
                        .IsRequired();

                    b.Navigation("IdmaTbNavigation");

                    b.Navigation("IdphongNavigation");
                });

            modelBuilder.Entity("_1_DAL.Entities.HoaDonBanHang", b =>
                {
                    b.HasOne("_1_DAL.Entities.CongThucTinh", "IdcongThucTinhNavigation")
                        .WithMany("HoaDonBanHangs")
                        .HasForeignKey("IdcongThucTinh")
                        .HasConstraintName("FK_HoaDonBanHang_CongThucTinh");

                    b.HasOne("_1_DAL.Entities.KhachHang", "IdmaKhNavigation")
                        .WithMany("HoaDonBanHangs")
                        .HasForeignKey("IdmaKh")
                        .HasConstraintName("FK_HoaDonBanHang_KhachHang");

                    b.HasOne("_1_DAL.Entities.NhanVien", "IdmaNvNavigation")
                        .WithMany("HoaDonBanHangs")
                        .HasForeignKey("IdmaNv")
                        .HasConstraintName("FK_HoaDonBanHang_NhanVien");

                    b.HasOne("_1_DAL.Entities.Phong", "IdphongNavigation")
                        .WithMany("HoaDonBanHangs")
                        .HasForeignKey("Idphong")
                        .HasConstraintName("FK_HoaDonBanHang_Phong");

                    b.Navigation("IdcongThucTinhNavigation");

                    b.Navigation("IdmaKhNavigation");

                    b.Navigation("IdmaNvNavigation");

                    b.Navigation("IdphongNavigation");
                });

            modelBuilder.Entity("_1_DAL.Entities.HoaDonNhap", b =>
                {
                    b.HasOne("_1_DAL.Entities.NhaCungCap", "IdnhaCcNavigation")
                        .WithMany("HoaDonNhaps")
                        .HasForeignKey("IdnhaCc")
                        .HasConstraintName("FK_HoaDonNhap_NhaCungCap1");

                    b.HasOne("_1_DAL.Entities.NhanVien", "IdnhanVienNhapNavigation")
                        .WithMany("HoaDonNhaps")
                        .HasForeignKey("IdnhanVienNhap")
                        .HasConstraintName("FK_HoaDonNhap_NhanVien")
                        .IsRequired();

                    b.Navigation("IdnhaCcNavigation");

                    b.Navigation("IdnhanVienNhapNavigation");
                });

            modelBuilder.Entity("_1_DAL.Entities.MatHang", b =>
                {
                    b.HasOne("_1_DAL.Entities.DonViTinh", "IddonViTinhNavigation")
                        .WithMany("MatHangs")
                        .HasForeignKey("IddonViTinh")
                        .HasConstraintName("FK_MatHang_DonViTinh");

                    b.Navigation("IddonViTinhNavigation");
                });

            modelBuilder.Entity("_1_DAL.Entities.NhanVien", b =>
                {
                    b.HasOne("_1_DAL.Entities.ChucVu", "IdchucVuNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("IdchucVu")
                        .HasConstraintName("FK_NhanVien_ChucVu");

                    b.Navigation("IdchucVuNavigation");
                });

            modelBuilder.Entity("_1_DAL.Entities.Phong", b =>
                {
                    b.HasOne("_1_DAL.Entities.LoaiPhong", "IdloaiPhongNavigation")
                        .WithMany("Phongs")
                        .HasForeignKey("IdloaiPhong")
                        .HasConstraintName("FK_Phong_LoaiPhong");

                    b.HasOne("_1_DAL.Entities.Tang", "IdtangNavigation")
                        .WithMany("Phongs")
                        .HasForeignKey("Idtang")
                        .HasConstraintName("FK_Phong_Tang");

                    b.Navigation("IdloaiPhongNavigation");

                    b.Navigation("IdtangNavigation");
                });

            modelBuilder.Entity("_1_DAL.Entities.ThietBi", b =>
                {
                    b.HasOne("_1_DAL.Entities.LoaiThietBi", "IdmaLoaiTbNavigation")
                        .WithMany("ThietBis")
                        .HasForeignKey("IdmaLoaiTb")
                        .HasConstraintName("FK_ThietBi_LoaiThietBi");

                    b.Navigation("IdmaLoaiTbNavigation");
                });

            modelBuilder.Entity("_1_DAL.Entities.ChucVu", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("_1_DAL.Entities.CongThucTinh", b =>
                {
                    b.Navigation("HoaDonBanHangs");
                });

            modelBuilder.Entity("_1_DAL.Entities.DonViTinh", b =>
                {
                    b.Navigation("MatHangs");
                });

            modelBuilder.Entity("_1_DAL.Entities.HoaDonBanHang", b =>
                {
                    b.Navigation("ChiTietHoaDonBans");
                });

            modelBuilder.Entity("_1_DAL.Entities.HoaDonNhap", b =>
                {
                    b.Navigation("ChiTietHoaDonNhaps");
                });

            modelBuilder.Entity("_1_DAL.Entities.KhachHang", b =>
                {
                    b.Navigation("HoaDonBanHangs");
                });

            modelBuilder.Entity("_1_DAL.Entities.LoaiPhong", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("_1_DAL.Entities.LoaiThietBi", b =>
                {
                    b.Navigation("ThietBis");
                });

            modelBuilder.Entity("_1_DAL.Entities.MatHang", b =>
                {
                    b.Navigation("ChiTietHoaDonBans");

                    b.Navigation("ChiTietHoaDonNhaps");
                });

            modelBuilder.Entity("_1_DAL.Entities.NhaCungCap", b =>
                {
                    b.Navigation("HoaDonNhaps");
                });

            modelBuilder.Entity("_1_DAL.Entities.NhanVien", b =>
                {
                    b.Navigation("HoaDonBanHangs");

                    b.Navigation("HoaDonNhaps");
                });

            modelBuilder.Entity("_1_DAL.Entities.Phong", b =>
                {
                    b.Navigation("ChiTietThietBis");

                    b.Navigation("HoaDonBanHangs");
                });

            modelBuilder.Entity("_1_DAL.Entities.Tang", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("_1_DAL.Entities.ThietBi", b =>
                {
                    b.Navigation("ChiTietThietBis");
                });
#pragma warning restore 612, 618
        }
    }
}
